In [2]:
#--------------------------------
# 1. import Library
#--------------------------------

import os
import sys
import pandas as pd
import numpy as np

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
os.chdir(PROJECT_ROOT)

if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

print("Current working directory:", os.getcwd())

Current working directory: c:\Users\venut\OneDrive\Documents\Projects\credit_risk_project

In [3]:
#--------------------------------
# 2. Load Dataset
#--------------------------------

df = pd.read_csv("data/raw/dataset.csv", low_memory=False)
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#--------------------------------
# 3. Dataset Shape
#--------------------------------

print("Shape of the dataset:", df.shape)

Shape of the dataset: (2260701, 151)

In [5]:
#--------------------------------
# 4. Dataset Columns
#--------------------------------

df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=151)

In [6]:
#--------------------------------
# 5. Dataset Info
#--------------------------------

df.info(verbose=False, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [7]:
#--------------------------------
# 6. Check for Duplicates
#--------------------------------

print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [8]:
#--------------------------------
# 7. Check Data Types
#--------------------------------

print("Data types of each column:")
print(df.dtypes)

Data types of each column:
id                        object
member_id                float64
loan_amnt                float64
funded_amnt              float64
funded_amnt_inv          float64
                          ...
settlement_status         object
settlement_date           object
settlement_amount        float64
settlement_percentage    float64
settlement_term          float64
Length: 151, dtype: object

In [9]:
#--------------------------------
# 8. Check for Missing Values
#--------------------------------
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:

id                             0
member_id                2260701
loan_amnt                     33
funded_amnt                   33
funded_amnt_inv               33
                          ...
settlement_status        2226455
settlement_date          2226455
settlement_amount        2226455
settlement_percentage    2226455
settlement_term          2226455
Length: 151, dtype: int64

In [10]:
#--------------------------------
# 9. Statistical Summary
#--------------------------------

df.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260639e+06,2.260668e+06,...,10917.0,10917.000000,10917.0,10917.000000,8651.000000,10917.000000,10917.000000,34246.000000,34246.000000,34246.000000
mean,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,3.068792e-01,6.985882e+02,...,3.0,155.045981,3.0,13.743886,454.798089,11636.883942,193.994321,5010.664267,47.780365,13.191322
std,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,8.672303e-01,3.301038e+01,...,0.0,129.040594,0.0,9.671178,375.385500,7625.988281,198.629496,3693.122590,7.311822,8.159980
min,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,0.000000e+00,6.750000e+02,...,3.0,59.440000,3.0,5.000000,175.230000,5627.000000,44.440000,2208.000000,45.000000,6.000000
50%,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,...,3.0,119.140000,3.0,15.000000,352.770000,10028.390000,133.160000,4146.110000,45.000000,14.000000
75%,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,0.000000e+00,7.150000e+02,...,3.0,213.260000,3.0,22.000000,620.175000,16151.890000,284.190000,6850.172500,50.000000,18.000000
max,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

In [11]:
#--------------------------------
# 10. Missing Value Analysis
#--------------------------------

missing = df.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({"Missing Count": missing, "Missing %": missing_pct})
missing_df[missing_df["Missing Count"] > 0].head(30)

                                            Missing Count   Missing %
member_id                                         2260701  100.000000
orig_projected_additional_accrued_interest        2252050   99.617331
hardship_reason                                   2249784   99.517097
hardship_payoff_balance_amount                    2249784   99.517097
hardship_last_payment_amount                      2249784   99.517097
payment_plan_start_date                           2249784   99.517097
hardship_type                                     2249784   99.517097
hardship_status                                   2249784   99.517097
hardship_start_date                               2249784   99.517097
deferral_term                                     2249784   99.517097
hardship_amount                                   2249784   99.517097
hardship_dpd                                      2249784   99.517097
hardship_loan_status                              2249784   99.517097
hardship_length                                   2249784   99.517097
hardship_end_date                                 2249784   99.517097
settlement_status                                 2226455   98.485160
debt_settlement_flag_date                         2226455   98.485160
settlement_term                                   2226455   98.485160
settlement_percentage                             2226455   98.485160
settlement_date                                   2226455   98.485160
settlement_amount                                 2226455   98.485160
sec_app_mths_since_last_major_derog               2224759   98.410139
sec_app_revol_util                                2154517   95.303050
revol_bal_joint                                   2152681   95.221836
sec_app_inq_last_6mths                            2152680   95.221792
sec_app_num_rev_accts                             2152680   95.221792
sec_app_open_acc                                  2152680   95.221792
sec_app_earliest_cr_line                          2152680   95.221792
sec_app_fico_range_high                           2152680   95.221792
sec_app_mort_acc                                  2152680   95.221792

In [12]:
#--------------------------------
# 12. Target Variable Distribution
#--------------------------------
df['loan_status'].value_counts()

loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: count, dtype: int64

In [13]:
#--------------------------------
# 11. Save Metadata
#--------------------------------
column_summary = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values,
    "Missing %": df.isnull().mean().values * 100
})

os.makedirs("data/metadata", exist_ok=True)
column_summary.to_csv("data/metadata/column_summary.csv", index=False)
print("Saved to data/metadata/column_summary.csv")

Saved to data/metadata/column_summary.csv

In [14]:
#--------------------------------
# 13. Business Insight
#--------------------------------
print("""
Important Business Observation:

- 'Current' loans are still active and do not represent final outcomes.
- For credit risk modeling, only completed loan outcomes should be used.
- Therefore:
    Good Loans  -> Fully Paid
    Bad Loans   -> Charged Off / Default
""")

Important Business Observation:

- 'Current' loans are still active and do not represent final outcomes.
- For credit risk modeling, only completed loan outcomes should be used.
- Therefore:
    Good Loans  -> Fully Paid
    Bad Loans   -> Charged Off / Default